---
- name: Installing fping
  apt:
    name: "{{ item }}"
  with_items:
    - fping

- name: Uploading the host list
  template:
    src: hosts.txt.j2
    dest: /tmp/hosts

- name: Get the latencies between all the nodes
  shell: "fping -C 10 -q -s -e -f /tmp/hosts 2>/tmp/result"

- name: Fetching the results
  fetch:
    src: /tmp/result
    dest: "/{{ tc_output_dir }}/{{ inventory_hostname }}.out"
    flat: yes
